GET http://localhost:3000/api/v1/tasks

###

GET http://localhost:3000/api/v1/tasks/609ed7ed041eec47df2c5a94

###

POST http://localhost:3000/api/v1/tasks
Content-Type: application/json

{
  "id": 3,
  "title": "Reading a book",
  "userId": "609ed4c7e65f90453bc24c78"
}

###

GET http://localhost:3000/api/v1/users

###

GET http://localhost:3000/api/v1/users/609ed4c7e65f90453bc24c78

###

POST http://localhost:3000/api/v1/users/signup
Content-Type: application/json

{
  "firstname": "David",
  "lastname": "Diaz",
  "email": "david.diaz@example.org",
  "password": "12345"
}

###

POST http://localhost:3000/api/v1/users/signin
Content-Type: application/json

{
  "email": "david.diaz@example.org",
  "password": "12345"
}

###

GET http://localhost:3000/api/v1/groups

###

GET http://localhost:3000/api/v1/groups/609ed8df831eba481420d3d3

###

POST http://localhost:3000/api/v1/groups
Content-Type: application/json

{
  "title": "nombre del grupo",
  "userId": "609ed4c7e65f90453bc24c78"
}