GET http://localhost:3000/api/v1/tasks

###

GET http://localhost:3000/api/v1/tasks/6098182db299fb1b36f3e8a9

###

POST http://localhost:3000/api/v1/tasks
Content-Type: application/json

{
  "id": 3,
  "title": "Reading a book"
}